
node('master')
node('loan') 
{
    stage('ContinuousDownload-master') 
    stage('ContinuousDownload-loan')
    
    {
       git 'https://github.com/selenium-saikrishna/maven.git'

    }
    stage('ContinuousBuild-master') 
    stage('ContinuousBuild-loan')
    {
      sh 'mvn package'
    }
    stage('ContinuousDeployment-master')
    stage('ContinuousDeployment-loan')
    {
        sh 'scp /home/ubuntu/.jenkins/workspace/multibranch/webapp/target/webapp.war ubuntu@172.31.28.128:/var/lib/tomcat7/webapps/qaenv.war'
    }
    stage('Continuoustesting-master')
    stage('Continuoustesting-loan')
    {
        git 'https://github.com/selenium-saikrishna/FunctionalTesting.git'
    }
    
    
 
    
    
    
}

